In [ ]:
top_3= df(salary).sort_values(ascending = false).head(3)
 print(top_3)

IndentationError: unexpected indent (4004609937.py, line 2)

# Topics covered

- GroupBy Operation
- Merge and Join operations
- Reshaping Data
- Combing Techinques

In [ ]:
import pandas as pd
import numpy as np

# Create a sample sales dataset

Columns include:
- Order ID
- Customer
- Region
- Product
- Sales Amount
- Quantity

In [ ]:
data = {
    'Order_ID': [101, 102, 103, 104, 105, 106, 107, 108],
    'Customer': ['Amit', 'Rahul','Sneha', 'Priya', 'Karan', 'Anita', 'Raj', 'Neha'],
    'Region': ['East', 'West', 'East', 'South', 'West', 'East', 'South', 'West'],
    'Product': ['Laptop', 'Phone', 'Tablet', 'Laptop','Tablet','Phone','Laptop','Tablet'],
    'Sales': [50000, 60000, 70000, 45000, 35000, 56000, 56000, 76000],
    'Quantity': [2, 3, 1, 2, 4, 3, 2, 5]
}

In [ ]:
data

{'Order_ID': [101, 102, 103, 104, 105, 106, 107, 108],
 'Customer': ['Amit',
  'Rahul',
  'Sneha',
  'Priya',
  'Karan',
  'Anita',
  'Raj',
  'Neha'],
 'Region': ['East', 'West', 'East', 'South', 'West', 'East', 'South', 'West'],
 'Product': ['Laptop',
  'Phone',
  'Tablet',
  'Laptop',
  'Tablet',
  'Phone',
  'Laptop',
  'Tablet'],
 'Sales': [50000, 60000, 70000, 45000, 35000, 56000, 56000, 76000],
 'Quantity': [2, 3, 1, 2, 4, 3, 2, 5]}

In [ ]:
df = pd.DataFrame(data)
df

   Order_ID Customer Region Product  Sales  Quantity
0       101     Amit   East  Laptop  50000         2
1       102    Rahul   West   Phone  60000         3
2       103    Sneha   East  Tablet  70000         1
3       104    Priya  South  Laptop  45000         2
4       105    Karan   West  Tablet  35000         4
5       106    Anita   East   Phone  56000         3
6       107      Raj  South  Laptop  56000         2
7       108     Neha   West  Tablet  76000         5

# GroupBy Operations

GroupBy allows us to group data based on a category and apply aggregation functions

This helps analysts summarize large datasets into meaningful insights

## Common Operations
- Total sales by region
- Average order value by product
- Quantity sold by category

In [ ]:
df.groupby('Region')['Sales'].sum()

Region
East     176000
South    101000
West     171000
Name: Sales, dtype: int64

In [ ]:
df.groupby('Product').agg({'Sales' : ['sum', 'mean'],'Quantity': ['mean']})

          Sales                Quantity
            sum          mean      mean
Product
Laptop   151000  50333.333333  2.000000
Phone    116000  58000.000000  3.000000
Tablet   181000  60333.333333  3.333333

# Merge and Join operations

In [ ]:
customers = pd.DataFrame({
    'Customer': ['Amit', 'Rahul', 'Sneha', 'Priya','Karan'],
    'City' : ['Mumbai', 'Delhi', 'Pune','Bangalore', 'Chennai']
})

In [ ]:
customers

  Customer       City
0     Amit     Mumbai
1    Rahul      Delhi
2    Sneha       Pune
3    Priya  Bangalore
4    Karan    Chennai

In [ ]:
orders = pd.DataFrame({
    'Customer': ['Amit', 'Rahul', 'Sneha', 'Raj', 'Neha'],
    'OrderValue': [50000, 20000, 30000, 48000, 27000]
})

In [ ]:
orders

  Customer  OrderValue
0     Amit       50000
1    Rahul       20000
2    Sneha       30000
3      Raj       48000
4     Neha       27000

In [ ]:
# INNER JOIN

pd.merge(customers, orders, on = 'Customer', how = 'inner')

  Customer    City  OrderValue
0     Amit  Mumbai       50000
1    Rahul   Delhi       20000
2    Sneha    Pune       30000

In [ ]:
# LEFT JOIN

pd.merge(customers, orders, on='Customer', how = 'left')

  Customer       City  OrderValue
0     Amit     Mumbai     50000.0
1    Rahul      Delhi     20000.0
2    Sneha       Pune     30000.0
3    Priya  Bangalore         NaN
4    Karan    Chennai         NaN

# Reshaping Data

In [ ]:
sales_data = pd.DataFrame({
    'Region': ['East', 'West','East','West'],
    'Product': ['Laptop', 'Laptop', 'Phone', 'Phone'],
    'Sales': [50000, 45000, 30000, 25000]
})

In [ ]:
sales_data

  Region Product  Sales
0   East  Laptop  50000
1   West  Laptop  45000
2   East   Phone  30000
3   West   Phone  25000

# Pivot Table

In [ ]:
pd.pivot_table(
    sales_data,
    index = 'Region',
    columns = 'Product',
    values = 'Sales',
    aggfunc = 'sum'
)

Product  Laptop  Phone
Region
East      50000  30000
West      45000  25000

# Melt Function

In [ ]:
monthly_sales = pd.DataFrame({
    'Product': ['Laptop', 'Phone'],
    'Jan': [20000, 15000],
    'Feb': [25000, 20000],
    'Mar': [30000, 35000]
})

In [ ]:
monthly_sales

  Product    Jan    Feb    Mar
0  Laptop  20000  25000  30000
1   Phone  15000  20000  35000

In [ ]:
pd.melt(monthly_sales, id_vars = ['Product'], var_name ='Month', value_name = 'Sales')

  Product Month  Sales
0  Laptop   Jan  20000
1   Phone   Jan  15000
2  Laptop   Feb  25000
3   Phone   Feb  20000
4  Laptop   Mar  30000
5   Phone   Mar  35000

# Stack and Unstack

In [ ]:
sales_data

  Region Product  Sales
0   East  Laptop  50000
1   West  Laptop  45000
2   East   Phone  30000
3   West   Phone  25000

In [ ]:
pivot = sales_data.pivot(index = 'Region', columns = 'Product', values = 'Sales')

In [ ]:
pivot

Product  Laptop  Phone
Region
East      50000  30000
West      45000  25000

In [ ]:
pivot.stack()

Region  Product
East    Laptop     50000
        Phone      30000
West    Laptop     45000
        Phone      25000
dtype: int64

# Concatenation Examples

In [ ]:
sales_q2 = pd.DataFrame({
    'Region': ['East', 'West'],
    'Laptop': [1500, 1080],
    'Phone': [950, 1100]
})

sales_q1 = pd.DataFrame({
    'Region': ['East', 'West'],
    'Laptop': [1200, 1500],
    'Phone': [800, 900]
})

sales_q3 = pd.DataFrame({
    'Region': ['East', 'West'],
    'Laptop': [1200, 1500],
    'Phone': [800, 900]
})

In [ ]:
sales_q1

  Region  Laptop  Phone
0   East    1200    800
1   West    1500    900

In [ ]:
sales_q2

  Region  Laptop  Phone
0   East    1500    950
1   West    1080   1100

In [ ]:
combines_sales = pd.concat([sales_q1, sales_q2, sales_q3])

In [ ]:
combines_sales

  Region  Laptop  Phone
0   East    1200    800
1   West    1500    900
0   East    1500    950
1   West    1080   1100
0   East    1200    800
1   West    1500    900

# Assignment

In [ ]:
df = pd.read_csv('/content/retail_dataset .csv')

In [ ]:
df.head(5)

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region
0,T001,C015,Books,7.0,167.0,02-02-2023,North
1,T002,C004,Toys,4.0,374.0,17-02-2023,South
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South
4,T005,C022,Books,7.0,282.0,27-07-2024,West

In [ ]:
df.shape

(100, 7)

In [ ]:
missing_values = df.isnull().sum()

In [ ]:
missing_values

Transaction ID      0
Customer ID         0
Product Category    3
Quantity            2
Price               5
Date                0
Region              2
dtype: int64

In [ ]:
missing_values.sum()

np.int64(12)

In [ ]:
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].mean())

In [ ]:
df['Price'] = df['Price'].fillna(df['Price'].mean())

In [ ]:
print(df[['Price', 'Quantity']].isnull().sum())

Price       0
Quantity    0
dtype: int64

In [ ]:
df = df.dropna(subset=['Product Category', 'Region'])

In [ ]:
df.shape

(95, 7)

In [ ]:
df['Revenue'] = np.multiply(df['Quantity'], df['Price'])

/tmp/ipykernel_762/1830166690.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Revenue'] = np.multiply(df['Quantity'], df['Price'])

In [ ]:
df.head()

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region,Revenue
0,T001,C015,Books,7.0,167.0,02-02-2023,North,1169.0
1,T002,C004,Toys,4.0,374.0,17-02-2023,South,1496.0
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South,8472.0
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South,1520.0
4,T005,C022,Books,7.0,282.0,27-07-2024,West,1974.0

In [ ]:
df['Revenue'].sum()

np.float64(465529.66058002145)

In [ ]:
category_revenue = df.groupby('Product Category')['Revenue'].sum()

category_revenue

Product Category
Beauty          27647.000000
Books           29597.938776
Clothing        85006.000000
Electronics     93204.315789
Furniture      129664.526316
Groceries       11978.000000
Sports          34484.000000
Toys            53947.879699
Name: Revenue, dtype: float64

In [ ]:
top_3_cat = category_revenue.sort_values(ascending = False).head(3)

In [ ]:
top_3_cat

Product Category
Furniture      129664.526316
Electronics     93204.315789
Clothing        85006.000000
Name: Revenue, dtype: float64

In [ ]:
bottom_3_cat = category_revenue.sort_values().head(3)

In [ ]:
bottom_3_cat

Product Category
Groceries    11978.000000
Beauty       27647.000000
Books        29597.938776
Name: Revenue, dtype: float64

In [ ]:
region_revenue = df.groupby('Region')['Revenue'].sum()

In [ ]:
region_revenue

Region
East     126232.044039
North    153244.353383
South    104855.736842
West      81197.526316
Name: Revenue, dtype: float64

In [ ]:
print(region_revenue.idxmax())

North

In [ ]:
print(region_revenue.idxmin())

West

In [ ]:
df['Date'] = pd.to_datetime(df['Date'], dayfirst = True)

/tmp/ipykernel_762/3923859410.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date'] = pd.to_datetime(df['Date'], dayfirst = True)

In [ ]:
df.head()

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region,Revenue
0,T001,C015,Books,7.0,167.0,2023-02-02,North,1169.0
1,T002,C004,Toys,4.0,374.0,2023-02-17,South,1496.0
2,T003,C033,Furniture,8.0,1059.0,2024-05-17,South,8472.0
3,T004,C047,Groceries,5.0,304.0,2024-02-11,South,1520.0
4,T005,C022,Books,7.0,282.0,2024-07-27,West,1974.0

In [ ]:
df['Month'] = df['Date'].dt.month_name()

/tmp/ipykernel_762/3416567508.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Month'] = df['Date'].dt.month_name()

In [ ]:
df.head()

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region,Revenue,Month
0,T001,C015,Books,7.0,167.0,2023-02-02,North,1169.0,February
1,T002,C004,Toys,4.0,374.0,2023-02-17,South,1496.0,February
2,T003,C033,Furniture,8.0,1059.0,2024-05-17,South,8472.0,May
3,T004,C047,Groceries,5.0,304.0,2024-02-11,South,1520.0,February
4,T005,C022,Books,7.0,282.0,2024-07-27,West,1974.0,July

In [ ]:
monthly_revenue = df.groupby('Month')['Revenue'].sum()

In [ ]:
monthly_revenue

Month
April        57298.526316
August       76958.000000
December     43339.000000
February     33028.000000
January      43994.000000
July         47851.292159
June         28190.000000
March        10557.000000
May          27915.000000
November     27662.736842
October      38017.000000
September    30719.105263
Name: Revenue, dtype: float64

In [ ]:
print(np.mean(df['Revenue']))

4900.312216631804

In [ ]:
print(np.median(df['Revenue']))

3282.1052631578946

In [ ]:
print(np.std(df['Revenue']))

4721.171795257337

# Excercise

In [ ]:
data = {
    'Department': ['HR', 'IT', 'HR', 'IT', 'Sales'],
    'Salary': [40000,50000, 60000, 50000, 50000]
}

df = pd.DataFrame(data)

In [ ]:
# Questions = Find the average salary department wise

In [ ]:
result = df.groupby('Department')['Salary'].mean()

In [ ]:
result

Department
HR       50000.0
IT       50000.0
Sales    50000.0
Name: Salary, dtype: float64

In [ ]:
data = {
    'Employee': ['A', 'B', 'C', 'D', 'E'],
    'Salary': [40000,50000, 60000, 50000, 50000]
}
df = pd.DataFrame(data)
print(df)

  Employee  Salary
0        A   40000
1        B   50000
2        C   60000
3        D   50000
4        E   50000

In [ ]:
# Top 3 employess with highest salaries

In [ ]:
unique df(set(employee))
print(unique)

SyntaxError: invalid syntax (753752665.py, line 1)